{
    "name": "Cars management Base",
    "version": "17.0.1.0.4",
    "author": "Wellknot",
    "depends": [
        "fleet",
        "utm",
        "hr",
        "portal",
        "sales_team",
        "infinito_sms",
        "sale",
        "im_livechat",
        "partner_autocomplete",
        "hr_branch_department",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/product_security.xml",
        "security/security_rules_cars_management.xml",
        "data/data.xml",
        "report/car_checkin_report_templates.xml",
        "report/car_checkout_report_templates.xml",
        "report/report.xml",
        "data/mail_template_data.xml",
        "data/customer_membership_level_data.xml",
        "views/menu.xml",
        "views/fleet_vehicle_model_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/vehicle_color_views.xml",
        "views/car_check_item_views.xml",
        "views/res_partner_views.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "views/product_attribute_views.xml",
        "views/car_checkin_views.xml",
        "views/car_checkout_views.xml",
        "views/payment_views.xml",
        "views/res_company_views.xml",
        "views/sale_order_views.xml",
        "views/checkin_portal_templates.xml",
        "views/checkout_portal_templates.xml",
        "views/customer_membership_level_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "cars_management/static/src/**/*",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3",
}
