{
    "name": "Portal Content",
    "version": "17.0.1.0.1",
    "author": "Wellknot",
    "depends": ["product"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/menu.xml",
        "views/product_product_views.xml",
        "views/portal_partner_views.xml",
        "views/portal_loyalty_program_views.xml",
        "views/portal_testimony_views.xml",
        "views/portal_statistic_views.xml",
        "views/portal_news_views.xml",
        "views/portal_aboutus_views.xml",
        "views/portal_faq_views.xml",
        "views/portal_offer_views.xml",
        "views/portal_branch_views.xml",
        "views/portal_warranty_views.xml",
        "views/portal_privacy_policy_views.xml",
        "views/portal_terms_conditions_views.xml",
        "views/portal_banner_views.xml",
        "views/portal_return_change_policy_views.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}
