from . import fleet_vehicle
from . import vehicle_color
from . import product_template
from . import res_partner
from . import car_checkin
from . import car_checkout
from . import car_check_item
from . import fleet_vehicle_model
from . import product_attribute_value
from . import product_product
from . import payment_transaction
from . import res_company
from . import sale_order
from . import avatar_mixin
from . import mail_guest
from . import customer_membership_level
