from . import product_prodcut
from . import car_appointment_slot
from . import car_appointment
from . import fleet_vehicle
from . import car_checkin
from . import sale_order
from . import res_partner
from . import res_company
from . import res_config_settings
from . import account_move
from . import message_model
from . import product_pricelist
