{
    "name": "Partner Management",
    "summary": "Contact type, city selection, customer mobile OTP, supervisor/subordinate links, and related sale orders",
    "version": "17.0.1.1.2",
    "author": "Wellknot",
    "category": "Contacts",
    "depends": [
        "base",
        "contacts",
        "mail",
        "sale",
        "sale_product_configurator",
        "account",
        "infinito_sms",
        "cars_management",
        "appointment_management",
        "work_orders",
        "commission",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "wizard/send_otp_wizard_views.xml",
        "views/res_city_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/car_appointment_views.xml",
        "views/car_work_order_views.xml",
        "views/car_workorder_service_views.xml",
        "views/product_product_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "partner_management/static/src/js/vehicle_size_configurator.js",
            "partner_management/static/src/js/vehicle_size_configurator.xml",
        ],
    },
    "installable": True,
    "license": "LGPL-3",
}
