from . import product_product
from . import portal_partner
from . import portal_loyalty_program
from . import portal_testimony
from . import portal_statistic
from . import portal_news
from . import portal_aboutus
from . import portal_faq
from . import portal_offer
from . import portal_branch
from . import portal_warranty
from . import portal_privacy_policy
from . import portal_banner
from . import portal_terms_conditions
from . import portal_return_change_policy
