from . import res_city
from . import res_partner
from . import sale_order
from . import fleet_vehicle
from . import product_template
from . import product_product
from . import car_appointment
from . import car_checkout
from . import car_workorder_service
from . import car_work_order
